AllCops:
  NewCops: enable

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/LineLength:
  Max: 82

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  CountComments: true
  Max: 25
  IgnoredMethods: []
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 1500

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Naming/BinaryOperatorParameterName:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/tty-config.rb"

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: err

Style/AccessorGrouping:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Style/RedundantFetchBlock:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  Enabled: false
